version: '3.1'

services:
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata

  nginx:
    container_name: loadbalance
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "443:443"
    environment:
      - NGINX_PORT=443